main: com.github.shatteredsoftware.welcomer.ShatteredWelcomer
name: ShatteredWelcomer
version: 1.0.0
author: UberPilot
api-version: 1.16
softdepend:
  - PlaceholderAPI
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.20